[package]
name = "rstar"
version = "0.1.1"
authors = ["Stefan Altmayer <stoeoef@gmail.com>"]
description = "R*-tree library for the rust ecosystem"
documentation = "https://docs.rs/rstar/"
repository = "https://github.com/Stoeoef/rstar"
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2018"
keywords = ["rtree", "rstar", "spatialgit-database", "nearest-neighbor"]
categories = ["data-structures", "algorithms"]

[badges]
gitlab = { repository = "https://github.com/Stoeoef/rstar" }

[dependencies]
num-traits = "0.2"
pdqselect = "0.1"

[features]
default = []
debug = []

[dev-dependencies]
rand = "0.6"
rand_hc = "0.1"
approx = "0.3"