[package]
name = "rstar"
version = "0.1.0"
authors = ["Stefan Altmayer <stoeoef@gmail.com>"]

[dependencies]
num-traits = "*"
pdqselect = "*"

[features]
default = []
debug = []

[dev-dependencies]
rand = "*"
approx = "*"