[package]
name = "rstar-benches"
version = "0.1.0"
authors = ["Stefan Altmayer <stoeoef@gmail.com>"]

[dev-dependencies]
rand = "0.7"
rand_hc = "0.2"
criterion = "0.2"
spade = "1.8"
rstar = { path = "../rstar" }

[[bench]]
name = "benchmarks"
harness = false
