[package]
name = "rstar-demo"
version = "0.1.0"
authors = ["Stefan Altmayer <stoeoef@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
kiss3d = "0.17"
nalgebra = "0.16"

rstar = { path="../rstar", features=["debug"] }