[package]
name = "rstar-demo"
version = "0.1.0"

[dependencies]
num-traits = "0.2"
glfw = "0.8"
glium = "0.15"
rand = "0.6"
rand_hc = "0.1.0"

[dependencies.rstar]
path = "../rstar"
features = ["debug"]
